using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("dz.mediaplayer.vlc")]
[assembly: AssemblyDescriptionAttribute("Media player implementation assembly based on VLC.")]
[assembly: AssemblyCompanyAttribute("Digital Zone")]
[assembly: AssemblyConfigurationAttribute("mono-2.0 release")]
[assembly: AssemblyVersionAttribute("0.4.0.0")]

